-- AlterTable
ALTER TABLE "Menu" ADD COLUMN IF NOT EXISTS "isTemporary" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Menu" ADD COLUMN IF NOT EXISTS "startDate" TIMESTAMP(3);
ALTER TABLE "Menu" ADD COLUMN IF NOT EXISTS "endDate" TIMESTAMP(3);
ALTER TABLE "Menu" ADD COLUMN IF NOT EXISTS "isFestive" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Menu" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Menu_isActive_endDate_idx" ON "Menu"("isActive", "endDate");
